# Binance Public Data Downloader Configuration

# Base settings
base_url: "https://data.binance.vision/data/futures/um/daily/"
output_directory: "./data"
log_directory: "./logs"

# Time range settings
time_range:
  start_date: "2025-01-01" # Format: YYYY-MM-DD
  end_date: "2025-01-02" # Format: YYYY-MM-DD or "latest" for current date

# Data types to download
data_types:
  aggTrades: true
  bookDepth: false
  bookTicker: false
  indexPriceKlines: true
  klines: true
  markPriceKlines: false
  metrics: false
  premiumIndexKlines: false
  trades: false

# Klines intervals (only applies to klines, indexPriceKlines, markPriceKlines, premiumIndexKlines)
kline_intervals:
  - "1d"
  - "4h"
  - "1h"
  - "15m"

# Trading pairs
trading_pairs:
  - "BTCUSDT"
  # Leave empty to download all available pairs from Binance API
  # Or specify specific pairs like:
  # - "BTCUSDT"
  # - "ETHUSDT"
  # - "ADAUSDT"

# Download settings
download:
  max_concurrent_downloads: 16
  retry_attempts: 3
  retry_delay: 5 # seconds
  rate_limit_delay: 0.1 # seconds between requests
  chunk_size: 8192 # bytes for download streaming

# File processing
file_processing:
  auto_extract: true
  delete_zip_after_extract: true
  overwrite_existing: false # Skip if CSV already exists (resume functionality)

# Logging
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  console_output: true
  file_output: true
  max_log_file_size: "100MB"
  backup_count: 5
